### ISSUE TITLE
ERC20 address verification from Stakecraft

### ISSUE THREAD

**Issue by Stakecraft** [BlockPILabs/testnets#324]
Provider name: Stakecraft
Discord Tag: novy4976
ERC20: 0x6215CF116c6a96872486cDC7cb50f52e515cCD15

**Comment by Mummyhap** [comment]
Identity is verified，please double check the ERC20 address on the leaderboard sheet and reply the confirmation here.

**Comment by Stakecraft** [comment]
@Mummyhap  I confirm, thanks!

**Comment by Mummyhap** [comment]
approved
