### ISSUE TITLE
ERC20 address verification from silent

### ISSUE THREAD

**Issue by silentnoname** [BlockPILabs/testnets#325]
Provider name: silent
Discord Tag: silent666
ERC20: 0x124d05e1cF1316141463224e3b9a9592044eE325

**Comment by Mummyhap** [comment]
Identity verified.  Please confirm your ERC20 address in the leaderboard and reply here.

**Comment by silentnoname** [comment]
I have changed my address.

**Comment by Mummyhap** [comment]
please confirm the address here https://docs.google.com/spreadsheets/d/1Cfi_5UhbseKsbDcJJMtwGIKToJPX7rWUZzLQsOxcGrU/edit?gid=326298494#gid=326298494

**Comment by silentnoname** [comment]
I confirm, thanks

**Comment by Mummyhap** [comment]
approved
