### ISSUE TITLE
ERC20 address verification from Enigma

### ISSUE THREAD

**Issue by Enigma-Validator** [BlockPILabs/testnets#328]
Provider name: Enigma
Discord Tag: enigma_validator
ERC20: 0xF404080E350E2E7A7Ad8E72b6bf5CB3aC8C1Caec

**Comment by Mummyhap** [comment]
dentity verified. Please confirm your ERC20 address in the leaderboard sheet and reply here.

**Comment by Enigma-Validator** [comment]
I confirm the address in the leaderboard

**Comment by Mummyhap** [comment]
approved
